In [6]:
import datetime
import pandas as pd
import plotly.express as px
from greykite.framework.templates.autogen.forecast_config import ForecastConfig, MetadataParam, ModelComponentsParam
from greykite.framework.benchmark.data_loader_ts import DataLoaderTS
from greykite.framework.templates.forecaster import Forecaster

In [7]:
#LOAD A MODEL


source_dir= "/Users/Edouard_1/code/TheLab75/ParisDeepAirProject/Model_greykite"

forecaster = Forecaster()

forecaster.load_forecast_result(
    source_dir,
    load_design_info=True)

In [3]:
#To save a modek 

#The destination_dir is a string of the saving location

destination_dir = "/Users/Edouard_1/code/TheLab75/ParisDeepAirProject/Model_greykite"

forecaster.dump_forecast_result(
    destination_dir,
    object_name="Model_arima_greykite",
    dump_design_info=True,
    overwrite_exist_dir=True)

In [4]:
df = pd.read_csv("/Users/Edouard_1/Downloads/cluster1_Ouest_test.csv",index_col="Date_time")

df = df.drop(columns="Unnamed: 0")
df

,PM25,PM10,NO2,O3,Pollution_peak,ATMO,sin_Month,cos_Month,sin_day,cos_day,confinement
Date_time,,,,,,,,,,,
2022-11-28,12.32,24.10,48.65,53.60,0,0,-0.866025,0.500000,-0.781831,0.623490,0
2022-11-29,17.04,27.27,69.00,47.00,0,0,-0.866025,0.500000,0.000000,1.000000,0
2022-11-30,17.67,31.65,46.58,42.15,0,0,-0.866025,0.500000,0.781831,0.623490,0
2022-12-01,22.85,32.04,38.62,25.10,0,1,-0.500000,0.866025,0.974928,-0.222521,0
2022-12-02,28.70,35.24,39.72,24.95,0,2,-0.500000,0.866025,0.433884,-0.900969,0
2022-12-03,19.83,23.61,32.00,13.55,0,0,-0.500000,0.866025,-0.433884,-0.900969,0
2022-12-04,24.10,31.37,34.75,14.90,0,1,-0.500000,0.866025,-0.974928,-0.222521,0

In [5]:
fig = result.plot()
plotly.io.show(fig)

NameError: name 'result' is not defined

In [ ]:
future_df = result.timeseries.make_future_dataframe(
    periods=7,
    include_history=False)

In [ ]:
model.predict(future_df)