In [14]:
import pandas as pd

#ici on lit le fichier CSV lié à la station du 18ème

df = pd.read_csv("/Users/Edouard_1/Deep Air project/ind_idf_agglo.csv")
#df["date"]= df[df.Date_time
df

,X,Y,FID,valeur,source,type_zone,code_zone,lib_zone,val_no2,val_so2,val_o3,val_pm10,val_pm25,couleur,x_lamb93,y_lamb93,date_ech,qualif
0,2.346831,48.861828,1,3,Airparif,UU,851,Unité urbaine de Paris,2.0,1.0,3.0,2.0,0,#84BF75,652080,6862620,2020/01/02 23:00:00+00,Bon
1,2.346831,48.861828,2,2,Airparif,UU,851,Unité urbaine de Paris,2.0,1.0,2.0,2.0,0,#84BF75,652080,6862620,2020/01/01 23:00:00+00,Très bon
2,2.346831,48.861828,3,4,Airparif,UU,851,Unité urbaine de Paris,2.0,1.0,1.0,4.0,0,#84BF75,652080,6862620,2019/12/31 23:00:00+00,Bon
3,2.346831,48.861828,4,8,Airparif,UU,851,Unité urbaine de Paris,3.0,1.0,1.0,8.0,0,#D82517,652080,6862620,2019/12/30 23:00:00+00,Mauvais
4,2.346831,48.861828,5,7,Airparif,UU,851,Unité urbaine de Paris,3.0,1.0,1.0,7.0,0,#F29400,652080,6862620,2019/12/29 23:00:00+00,Médiocre
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
756,2.346831,48.861828,1358,3,Airparif,UU,851,Unité urbaine de Paris,2.0,1.0,3.0,3.0,0,#84BF75,652080,6862620,2021/02/11 23:00:00+00,Bon
757,2.346831,48.861828,1359,3,Airparif,UU,851,Unité urbaine de Paris,2.0,1.0,3.0,3.0,0,#84BF75,652080,6862620,2021/02/12 23:00:00+00,Bon
758,2.346831,48.861828,1360,3,Airparif,UU,851,Unité urbaine de Paris,2.0,1.0,2.0,3.0,0,#84BF75,652080,6862620,2021/02/13 23:00:00+00,Bon
759,2.346831,48.861828,1361,3,Airparif,UU,851,Unité urbaine de Paris,2.0,1.0,3.0,2.0,0,#84BF75,652080,6862620,2021/02/14 23:00:00+00,Bon
760,2.346831,48.861828,1362,3,Airparif,UU,851,Unité urbaine de Paris,NaN,NaN,NaN,NaN,0,#84BF75,652080,6862620,2021/02/15 23:00:00+00,Bon

In [15]:
def analyse_df(df, corr_limit = 0.75):
    """Analyse any dataframe and print results
    * Print df Shape, duplicate rows qnt, memory usage, data types and call DataFrame.describe()
    * Check Missing values in each columns, returning qnt. and percentage 
    * Check Linear Correlation between columns, return Pearson number
    Keyword arguments:
    df -- Any DataFrame
    corr_limit -- Correlation Limit (Pearson) to define if relationship exists (default 0.75)
    """   

    print('General Info:')
    print(f'{df.shape[0]} Rows {df.shape[1]} Columns'
          f'\n{df.duplicated().sum()} Duplicated Rows'
          f'\nMemory Usage: {df.memory_usage().sum()/(1024*1024):.2f}Mb')
    
    # Checking Data Types
    int_list, float_list,object_list,bool_list,other_list =[[] for i in range(5)]
    for col in df.columns:
        if df[col].dtype == 'int64':
            int_list.append(col)
        elif df[col].dtype == 'float64':
            float_list.append(col)
        elif df[col].dtype == 'object':
            object_list.append(col)
        elif df[col].dtype == 'boolean':
            bool_list.append(col)
        else:
            other_list.append(col)
            
    for type_list,data_type in zip([int_list, float_list,object_list,bool_list,other_list],
                                   ['int64','float64','object','boolean','other']):
        if len(type_list)>0:
            print(f'\nColumns {data_type}: {type_list}')
            
    # General statistics
    display(df.describe())
    
    # Checking Missing Values in each columns
    print('\nCheking Missing Values:')
    col_with_missing_counter = 0
    for col in df.columns:
        qnt_missing = df[col].isna().sum()
        if qnt_missing > 0:
            col_with_missing_counter +=1
            print(f'Column "{col}" has {qnt_missing} missing values ({qnt_missing/df.shape[0]:.2%})')
    if col_with_missing_counter ==0 :
        print('Analyzed DataFrame has no missing values')
        
    # Checking linear correlation between columns
    print('\nChecking Linear Correlation:')
    df_corr = df.corr() # Correlation DataFrame
    ckecked_list =[] # Ensure that we won't print the same information twice
    cols_with_correlation_counter = 0
    for col in df_corr.columns:
        ckecked_list.append(col)
        for i in range(len(df_corr)):
            if ((df_corr[col][i] > corr_limit or df_corr[col][i] < -corr_limit) and
                (df_corr.index[i] not in ckecked_list)):
                cols_with_correlation_counter += 1
                print(f'Linear Correlation found between columns '
                      f'{df_corr.index[i]} and {col} -> Pearson coef. = {df_corr[col][i]:.2f}')         
    if cols_with_correlation_counter == 0:
        print('No linear correlation was found')

In [16]:
analyse_df(df)

General Info:
761 Rows 18 Columns
0 Duplicated Rows
Memory Usage: 0.10Mb

Columns int64: ['FID', 'valeur', 'code_zone', 'val_pm25', 'x_lamb93', 'y_lamb93']

Columns float64: ['X', 'Y', 'val_no2', 'val_so2', 'val_o3', 'val_pm10']

Columns object: ['source', 'type_zone', 'lib_zone', 'couleur', 'date_ech', 'qualif']

,X,Y,FID,valeur,code_zone,val_no2,val_so2,val_o3,val_pm10,val_pm25,x_lamb93,y_lamb93
count,7.610000e+02,7.610000e+02,761.000000,761.000000,761.0,753.000000,753.000000,753.000000,753.000000,761.0,761.0,761.0
mean,2.346831e+00,4.886183e+01,627.402102,3.806833,851.0,2.163347,0.998672,3.312085,3.088977,0.0,652080.0,6862620.0
std,2.488535e-14,4.479363e-13,496.580556,1.195718,0.0,0.801352,0.036442,1.173545,1.251084,0.0,0.0,0.0
min,2.346831e+00,4.886183e+01,1.000000,2.000000,851.0,1.000000,0.000000,1.000000,1.000000,0.0,652080.0,6862620.0
25%,2.346831e+00,4.886183e+01,191.000000,3.000000,851.0,2.000000,1.000000,3.000000,2.000000,0.0,652080.0,6862620.0
50%,2.346831e+00,4.886183e+01,381.000000,3.000000,851.0,2.000000,1.000000,3.000000,3.000000,0.0,652080.0,6862620.0
75%,2.346831e+00,4.886183e+01,1172.000000,4.000000,851.0,3.000000,1.000000,4.000000,4.000000,0.0,652080.0,6862620.0
max,2.346831e+00,4.886183e+01,1362.000000,8.000000,851.0,5.000000,1.000000,8.000000,8.000000,0.0,652080.0,6862620.0

Cheking Missing Values:
Column "val_no2" has 8 missing values (1.05%)
Column "val_so2" has 8 missing values (1.05%)
Column "val_o3" has 8 missing values (1.05%)
Column "val_pm10" has 8 missing values (1.05%)

Checking Linear Correlation:
Linear Correlation found between columns val_pm10 and valeur -> Pearson coef. = 0.80

In [17]:
df.sort_values(by="date_ech")

,X,Y,FID,valeur,source,type_zone,code_zone,lib_zone,val_no2,val_so2,val_o3,val_pm10,val_pm25,couleur,x_lamb93,y_lamb93,date_ech,qualif
364,2.346831,48.861828,365,4,Airparif,UU,851,Unité urbaine de Paris,3.0,1.0,2.0,4.0,0,#84BF75,652080,6862620,2019/01/03 23:00:00+00,Bon
363,2.346831,48.861828,364,4,Airparif,UU,851,Unité urbaine de Paris,2.0,1.0,2.0,4.0,0,#84BF75,652080,6862620,2019/01/04 23:00:00+00,Bon
362,2.346831,48.861828,363,5,Airparif,UU,851,Unité urbaine de Paris,3.0,1.0,2.0,5.0,0,#F29400,652080,6862620,2019/01/05 23:00:00+00,Moyen
361,2.346831,48.861828,362,4,Airparif,UU,851,Unité urbaine de Paris,3.0,1.0,2.0,4.0,0,#84BF75,652080,6862620,2019/01/06 23:00:00+00,Bon
360,2.346831,48.861828,361,3,Airparif,UU,851,Unité urbaine de Paris,2.0,1.0,3.0,3.0,0,#84BF75,652080,6862620,2019/01/07 23:00:00+00,Bon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
756,2.346831,48.861828,1358,3,Airparif,UU,851,Unité urbaine de Paris,2.0,1.0,3.0,3.0,0,#84BF75,652080,6862620,2021/02/11 23:00:00+00,Bon
757,2.346831,48.861828,1359,3,Airparif,UU,851,Unité urbaine de Paris,2.0,1.0,3.0,3.0,0,#84BF75,652080,6862620,2021/02/12 23:00:00+00,Bon
758,2.346831,48.861828,1360,3,Airparif,UU,851,Unité urbaine de Paris,2.0,1.0,2.0,3.0,0,#84BF75,652080,6862620,2021/02/13 23:00:00+00,Bon
759,2.346831,48.861828,1361,3,Airparif,UU,851,Unité urbaine de Paris,2.0,1.0,3.0,2.0,0,#84BF75,652080,6862620,2021/02/14 23:00:00+00,Bon
760,2.346831,48.861828,1362,3,Airparif,UU,851,Unité urbaine de Paris,NaN,NaN,NaN,NaN,0,#84BF75,652080,6862620,2021/02/15 23:00:00+00,Bon